# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('fromtime', models.DateField()),
                ('totime', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('skype', models.CharField(max_length=30)),
                ('website', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='cv.Person'),
        ),
    ]
