# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=60)),
                ('institution_website', models.URLField(max_length=60)),
                ('faculty', models.CharField(max_length=140)),
                ('fromtime', models.DateField()),
                ('totime', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KeySkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('skype', models.CharField(max_length=30)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkExpirience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('fromtime', models.DateField()),
                ('totime', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
