# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20160714_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
