# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_auto_20160715_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution_website',
            field=models.URLField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='education',
            name='ref',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='edu', to='cv.Person'),
        ),
        migrations.AlterField(
            model_name='education',
            name='totime',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='totime',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='keyskills',
            name='ref',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='cv.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, upload_to='/media/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='skype',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='website',
            field=models.URLField(blank=True, verbose_name='Homepage url'),
        ),
    ]
