# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_auto_20160715_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='totime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='totime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
