# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_auto_20160715_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo/'),
        ),
    ]
