# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 20:46
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0015_auto_20160717_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='photo/'),
        ),
    ]
